export class Conference {
  /** unique id, auto generated by server */
  id: string;
  /** min len: 1, max len: 100 */
  name: string;
  /** unix timestamp in millseconds */
  startDate: number;
  /** unix timestamp in millseconds */
  endDate: number;
  /** min len: 1, max len: 100 */
  url: string;
  /** not required, max len: 100 */
  location: string;
  /** not required, max len: 2000 */
  description: string;

  constructor() {
    this.id = '';
    this.name = '';
    this.startDate = 0;
    this.endDate = 0;
    this.url = '';
    this.location = '';
    this.description = '';
  }

  public set(data) {
    this.id = data.id;
    this.name = data.name;
    this.startDate = data.startDate;
    this.endDate = data.endDate;
    this.url = data.url;
    this.location = data.location;
    this.description = data.description;
  }
}
