export class User {
  /** unique id, auto generated by server */
  id: string = "";
  /** min len: 1, max len: 30 */
  email: string = "";
  /** min len: 1, max len: 20 */
  firstName: string = "";
  /** min len: 0, max len: 20 */
  MidName: string = "";
  /** min len: 1, max len: 20 */
  LastName: string = "";
  /** min len: 1, max len: 20 */
  city: string = "";
  /** min len: 1, max len: 20 */
  country: string = "";
  /** min len: 1, max len: 20 */
  department: string = "";
}
